<a href="https://colab.research.google.com/github/leapen2024/-Artificial-Intelligence-A-Z-2024-Build-7-AI-LLM-ChatGPT/blob/main/QLearningArthurJuliani.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

#Q-Table Learning
import gym
import numpy as np

#Load the environment
env = gym.make('FrozenLake-v1')

#Implement Q-Table learning algorithm
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)
print ("Score over time: " +  str(sum(rList)/num_episodes))
print ("Final Q-Table Values")
print (Q)

Score over time: 0.381
Final Q-Table Values
[[2.70301332e-03 4.01143869e-02 3.68902226e-03 2.73064328e-03]
 [4.73408232e-04 8.65214772e-05 8.91396501e-05 2.25256020e-02]
 [9.24973465e-04 4.05425929e-04 5.04933487e-04 1.33421931e-02]
 [4.29189847e-04 1.55871306e-05 2.01758741e-05 1.16409848e-02]
 [4.19775638e-02 5.18053499e-04 2.19100560e-03 4.48627324e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.27806357e-02 1.47825596e-05 5.29339720e-06 3.49485374e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.14126409e-04 3.97491100e-04 2.36599134e-03 2.20994252e-01]
 [1.99630173e-03 6.48012399e-01 5.99333781e-04 1.81307082e-03]
 [1.99233653e-01 3.07777050e-04 1.56079715e-04 5.50467025e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 7.90520697e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 9.67730857e-01]
 [0.0000000